// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSchedule.Data;

#nullable disable

namespace SchoolSchedule.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolSchedule.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassCode")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("(CAST([Grade] AS VARCHAR) + CAST([Section] AS VARCHAR))", true);

                    b.Property<string>("ClassName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("(CAST([Grade] AS VARCHAR) + '/' + CAST([Section] AS VARCHAR))", true);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.HasKey("ClassId");

                    b.HasIndex("Grade", "Section")
                        .IsUnique();

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1430),
                            Grade = 6,
                            IsActive = true,
                            Section = 1
                        },
                        new
                        {
                            ClassId = 2,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1438),
                            Grade = 6,
                            IsActive = true,
                            Section = 2
                        },
                        new
                        {
                            ClassId = 3,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1441),
                            Grade = 6,
                            IsActive = true,
                            Section = 3
                        },
                        new
                        {
                            ClassId = 4,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1444),
                            Grade = 6,
                            IsActive = true,
                            Section = 4
                        },
                        new
                        {
                            ClassId = 5,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1447),
                            Grade = 6,
                            IsActive = true,
                            Section = 5
                        },
                        new
                        {
                            ClassId = 6,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1451),
                            Grade = 6,
                            IsActive = true,
                            Section = 6
                        },
                        new
                        {
                            ClassId = 7,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1454),
                            Grade = 6,
                            IsActive = true,
                            Section = 7
                        },
                        new
                        {
                            ClassId = 8,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1456),
                            Grade = 6,
                            IsActive = true,
                            Section = 8
                        },
                        new
                        {
                            ClassId = 9,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1459),
                            Grade = 6,
                            IsActive = true,
                            Section = 9
                        },
                        new
                        {
                            ClassId = 10,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1464),
                            Grade = 7,
                            IsActive = true,
                            Section = 1
                        },
                        new
                        {
                            ClassId = 11,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1467),
                            Grade = 7,
                            IsActive = true,
                            Section = 2
                        },
                        new
                        {
                            ClassId = 12,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1469),
                            Grade = 7,
                            IsActive = true,
                            Section = 3
                        },
                        new
                        {
                            ClassId = 13,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1472),
                            Grade = 7,
                            IsActive = true,
                            Section = 4
                        },
                        new
                        {
                            ClassId = 14,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1475),
                            Grade = 7,
                            IsActive = true,
                            Section = 5
                        },
                        new
                        {
                            ClassId = 15,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1478),
                            Grade = 7,
                            IsActive = true,
                            Section = 6
                        },
                        new
                        {
                            ClassId = 16,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1481),
                            Grade = 7,
                            IsActive = true,
                            Section = 7
                        },
                        new
                        {
                            ClassId = 17,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1484),
                            Grade = 7,
                            IsActive = true,
                            Section = 8
                        },
                        new
                        {
                            ClassId = 18,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1488),
                            Grade = 7,
                            IsActive = true,
                            Section = 9
                        },
                        new
                        {
                            ClassId = 19,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1491),
                            Grade = 8,
                            IsActive = true,
                            Section = 1
                        },
                        new
                        {
                            ClassId = 20,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1494),
                            Grade = 8,
                            IsActive = true,
                            Section = 2
                        },
                        new
                        {
                            ClassId = 21,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1497),
                            Grade = 8,
                            IsActive = true,
                            Section = 3
                        },
                        new
                        {
                            ClassId = 22,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1499),
                            Grade = 8,
                            IsActive = true,
                            Section = 4
                        },
                        new
                        {
                            ClassId = 23,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1502),
                            Grade = 8,
                            IsActive = true,
                            Section = 5
                        },
                        new
                        {
                            ClassId = 24,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1505),
                            Grade = 8,
                            IsActive = true,
                            Section = 6
                        },
                        new
                        {
                            ClassId = 25,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1508),
                            Grade = 8,
                            IsActive = true,
                            Section = 7
                        },
                        new
                        {
                            ClassId = 26,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1511),
                            Grade = 8,
                            IsActive = true,
                            Section = 8
                        },
                        new
                        {
                            ClassId = 27,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1514),
                            Grade = 8,
                            IsActive = true,
                            Section = 9
                        },
                        new
                        {
                            ClassId = 28,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1517),
                            Grade = 9,
                            IsActive = true,
                            Section = 1
                        },
                        new
                        {
                            ClassId = 29,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1520),
                            Grade = 9,
                            IsActive = true,
                            Section = 2
                        },
                        new
                        {
                            ClassId = 30,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1523),
                            Grade = 9,
                            IsActive = true,
                            Section = 3
                        },
                        new
                        {
                            ClassId = 31,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1525),
                            Grade = 9,
                            IsActive = true,
                            Section = 4
                        },
                        new
                        {
                            ClassId = 32,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1528),
                            Grade = 9,
                            IsActive = true,
                            Section = 5
                        },
                        new
                        {
                            ClassId = 33,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1531),
                            Grade = 9,
                            IsActive = true,
                            Section = 6
                        },
                        new
                        {
                            ClassId = 34,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1535),
                            Grade = 9,
                            IsActive = true,
                            Section = 7
                        },
                        new
                        {
                            ClassId = 35,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1538),
                            Grade = 9,
                            IsActive = true,
                            Section = 8
                        },
                        new
                        {
                            ClassId = 36,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1541),
                            Grade = 9,
                            IsActive = true,
                            Section = 9
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Models.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("PeriodId");

                    b.HasIndex("PeriodNumber")
                        .IsUnique();

                    b.ToTable("Periods", (string)null);

                    b.HasData(
                        new
                        {
                            PeriodId = 1,
                            EndTime = new TimeSpan(0, 8, 15, 0, 0),
                            IsActive = true,
                            PeriodNumber = 1,
                            StartTime = new TimeSpan(0, 7, 30, 0, 0)
                        },
                        new
                        {
                            PeriodId = 2,
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            IsActive = true,
                            PeriodNumber = 2,
                            StartTime = new TimeSpan(0, 8, 15, 0, 0)
                        },
                        new
                        {
                            PeriodId = 3,
                            EndTime = new TimeSpan(0, 9, 45, 0, 0),
                            IsActive = true,
                            PeriodNumber = 3,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            PeriodId = 4,
                            EndTime = new TimeSpan(0, 10, 45, 0, 0),
                            IsActive = true,
                            PeriodNumber = 4,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            PeriodId = 5,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsActive = true,
                            PeriodNumber = 5,
                            StartTime = new TimeSpan(0, 10, 45, 0, 0)
                        },
                        new
                        {
                            PeriodId = 6,
                            EndTime = new TimeSpan(0, 12, 15, 0, 0),
                            IsActive = true,
                            PeriodNumber = 6,
                            StartTime = new TimeSpan(0, 11, 30, 0, 0)
                        },
                        new
                        {
                            PeriodId = 7,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            IsActive = true,
                            PeriodNumber = 7,
                            StartTime = new TimeSpan(0, 12, 15, 0, 0)
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<int?>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DayId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ClassId", "DayId", "PeriodId", "AcademicYear", "Semester")
                        .IsUnique()
                        .HasFilter("[AcademicYear] IS NOT NULL AND [Semester] IS NOT NULL");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("SchoolSchedule.Models.SchoolDay", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayId"));

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DayNameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DayId");

                    b.HasIndex("DayOrder")
                        .IsUnique();

                    b.ToTable("SchoolDays", (string)null);

                    b.HasData(
                        new
                        {
                            DayId = 1,
                            DayName = "الأحد",
                            DayNameEn = "Sunday",
                            DayOrder = 1,
                            IsActive = true
                        },
                        new
                        {
                            DayId = 2,
                            DayName = "الاثنين",
                            DayNameEn = "Monday",
                            DayOrder = 2,
                            IsActive = true
                        },
                        new
                        {
                            DayId = 3,
                            DayName = "الثلاثاء",
                            DayNameEn = "Tuesday",
                            DayOrder = 3,
                            IsActive = true
                        },
                        new
                        {
                            DayId = 4,
                            DayName = "الأربعاء",
                            DayNameEn = "Wednesday",
                            DayOrder = 4,
                            IsActive = true
                        },
                        new
                        {
                            DayId = 5,
                            DayName = "الخميس",
                            DayNameEn = "Thursday",
                            DayOrder = 5,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Models.SchoolSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAcademicYear")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<string>("EducationalZone")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PeriodsPerDay")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("SemesterStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingId");

                    b.ToTable("SchoolSettings", (string)null);

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(659),
                            CurrentAcademicYear = "2025/2026",
                            CurrentSemester = 2,
                            EducationalZone = "الادارة العامة لمنطقة حولى التعليمية",
                            PeriodsPerDay = 7,
                            SchoolName = "مدرسة عبدالمحسن الخرافى المتوسطة للبنين",
                            SemesterStartDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects", (string)null);

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1255),
                            IsActive = true,
                            SubjectName = "التربية الإسلامية",
                            SubjectNameEn = "Islamic Education"
                        },
                        new
                        {
                            SubjectId = 2,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1265),
                            IsActive = true,
                            SubjectName = "اللغة العربية",
                            SubjectNameEn = "Arabic Language"
                        },
                        new
                        {
                            SubjectId = 3,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1268),
                            IsActive = true,
                            SubjectName = "اللغة الإنجليزية",
                            SubjectNameEn = "English Language"
                        },
                        new
                        {
                            SubjectId = 4,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1271),
                            IsActive = true,
                            SubjectName = "الرياضيات",
                            SubjectNameEn = "Mathematics"
                        },
                        new
                        {
                            SubjectId = 5,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1369),
                            IsActive = true,
                            SubjectName = "العلوم",
                            SubjectNameEn = "Science"
                        },
                        new
                        {
                            SubjectId = 6,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1373),
                            IsActive = true,
                            SubjectName = "الاجتماعيات",
                            SubjectNameEn = "Social Studies"
                        },
                        new
                        {
                            SubjectId = 7,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1376),
                            IsActive = true,
                            SubjectName = "الحاسوب",
                            SubjectNameEn = "Computer"
                        },
                        new
                        {
                            SubjectId = 8,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1378),
                            IsActive = true,
                            SubjectName = "التربية البدنية",
                            SubjectNameEn = "Physical Education"
                        },
                        new
                        {
                            SubjectId = 9,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1381),
                            IsActive = true,
                            SubjectName = "التربية الموسيقية",
                            SubjectNameEn = "Music"
                        },
                        new
                        {
                            SubjectId = 10,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1383),
                            IsActive = true,
                            SubjectName = "التربية الفنية",
                            SubjectNameEn = "Art"
                        },
                        new
                        {
                            SubjectId = 11,
                            CreatedDate = new DateTime(2026, 3, 2, 20, 19, 47, 149, DateTimeKind.Local).AddTicks(1386),
                            IsActive = true,
                            SubjectName = "الدراسات العملية",
                            SubjectNameEn = "Practical Studies"
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHeadOfDepartment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("SchoolSchedule.Models.Schedule", b =>
                {
                    b.HasOne("SchoolSchedule.Models.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Models.SchoolDay", "SchoolDay")
                        .WithMany("Schedules")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Models.Period", "Period")
                        .WithMany("Schedules")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Models.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Models.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Period");

                    b.Navigation("SchoolDay");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSchedule.Models.Teacher", b =>
                {
                    b.HasOne("SchoolSchedule.Models.Subject", "Subject")
                        .WithMany("Teachers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolSchedule.Models.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SchoolSchedule.Models.Period", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SchoolSchedule.Models.SchoolDay", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SchoolSchedule.Models.Subject", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SchoolSchedule.Models.Teacher", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
